version: '3.9'

volumes:
  postgres_data:

services:
  storage:
    image: 'postgres:13.7'
    container_name: storage
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'su postgres', '&&', 'pg_isready' ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: truestore
      POSTGRES_PASSWORD: password

  backendapp:
    build:
      context: backend
      dockerfile: src/Dockerfile
    container_name: backendapp
    ports:
      - '8080:8080'
    depends_on:
      storage:
        condition: service_healthy
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://storage:5432/truestore
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=password
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

  webclient:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:8080
    container_name: webclient
    ports:
      - '80:80'
    depends_on:
      - backendapp
