/* eslint-disable no-undef */
const $HOST = 'http://localhost:8080';

export const routes = {
  pages: {
    loginPagePath: () => '/login',
    signupPagePath: () => '/signup',
    mainPagePath: () => '/applications',
    appsPagePath: () => '/:id',
    appPagePath: (id: string) => `/${id}`,
    newAppPagePath: () => '/newApp',
    userReportsPagePath: () => '/myReports',
    userAppsPagePath: () => '/myApps',
    profilePagePath: () => '/profile',
    landingPage: () => '/',
  },
  api: {
    loginPath: () => '/users/login',
    signupPath: () => '/users/signup',
    apps: () => '/apps',
    app: (id: string) => `/apps/${id}`,
    userApps: () => '/apps/my',
    userInfo: () => '/users/me',
    contracts: () => '/contracts',
    contract: (id: string) => `/contracts/${id}`,
    myContract: () => '/contracts/my',
    reports: () => '/reports',
    reportsWithParam: (param: string) => `/reports/${param}`,
    reportsByApp: (appId: string) => `/reports/app/${appId}`,
    reportsByContractId: (contractId: string) => `/reports/contract/${contractId}/my`,
    userReports: () => '/reports/my',
    approveReport: (reportId: string) => `reports/${reportId}/approve`,
    rejectReport: (reportId: string) => `reports/${reportId}/reject`,
    withdrawalMoney: () => '/money/withdrawal',
    replenishmentMoney: () => '/money/replenishment',
    userTransitions: () => '/money/my',
    userBalance: () => '/money/balance',
    messages: () => '/messages',
    messagesByContract: (contractId: string) => `/messages/contract/${contractId}`,
    messagesByApp: (appId: string) => `/messages/contract/${appId}`,
    basePath: () => process.env.BACKEND_HOST ?? $HOST,
  },
};
